# Generated by Django 2.2.20 on 2021-04-11 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0083_orderround_distribution_mails_sent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'base_manager_name': 'objects', 'verbose_name': 'Bestelling', 'verbose_name_plural': 'Bestellingen'},
        ),
        migrations.AlterModelOptions(
            name='orderproductcorrection',
            options={'base_manager_name': 'objects', 'verbose_name': 'Productbestelling-correctie', 'verbose_name_plural': 'Productbestelling-correcties'},
        ),
    ]
