# Generated by Django 2.2.20 on 2021-04-11 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0018_auto_20170502_0904'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='balance',
            options={'base_manager_name': 'objects'},
        ),
    ]
